/*
 * DlgGantiKota.java
 *
 * Created on March 29, 2008, 7:17 AM
 */

package tpjkeuangan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author  oestadho
 */
public class DlgGantiKota extends javax.swing.JDialog {
    private ListRsbm lst;
    Connection conn;
    Utama fMain=new Utama();
    private DefaultListModel lstKodeKota=new DefaultListModel();
    private DefaultListModel lstKotaSingkatan=new DefaultListModel();

    /** Creates new form DlgGantiKota */
    public DlgGantiKota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    void setConn(Connection con){
        conn=con;
    }

    void setMainForm(Utama aThis) {
        fMain=aThis;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblKotaRecent = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbKota = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ubah kota tujuan");
        setBackground(new java.awt.Color(51, 51, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnUpdate.setText("Ubah");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Kota saat ini ");

        lblKotaRecent.setBackground(new java.awt.Color(204, 255, 255));
        lblKotaRecent.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblKotaRecent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKotaRecent.setOpaque(true);

        jLabel3.setText("Ganti ke kota");

        cmbKota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbKotaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKotaRecent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbKota, 0, 262, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKotaRecent, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(cmbKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-425)/2, (screenSize.height-172)/2, 425, 172);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lst = new ListRsbm();
        lst.setVisible(false);
        lst.setSize(500, 200);
        lst.con = conn;
        
        lblKotaRecent.setText(Utama.sNamaKota);
        try{
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(   "select kode_kota, coalesce(nama_kota, '') as nama_kota, " +
                                            "coalesce(singkatan,'') as singkatan from kota order by nama_kota");

            lstKodeKota.removeAllElements();

            int idx=0;
            lstKodeKota.add(idx, "");
            lstKotaSingkatan.add(idx, "");

            cmbKota.addItem("<Semua Kota>");
            idx++;

            while(rs.next()){
                cmbKota.addItem(rs.getString("nama_kota"));
                lstKodeKota.add(idx, rs.getString("kode_kota"));
                lstKotaSingkatan.add(idx, rs.getString("singkatan"));
                idx++;
            }

        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//        if(JOptionPane.showConfirmDialog(this, "Ubah kota?", "Confirm", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
//            if(txtKotaTujuan.getText().trim().equalsIgnoreCase("")){
//                Utama.sKodeKota=txtKotaTujuan.getText();
//                Utama.sNamaKota="<Semua Kota>";
//                fMain.setKodeKota(txtKotaTujuan.getText());
//                fMain.setNamaKota("<Semua Kota>");
//            }else{
//                Utama.sKodeKota=txtKotaTujuan.getText();
//                Utama.sNamaKota=lblKotaTujuan.getText();
//                fMain.setKodeKota(txtKotaTujuan.getText());
//                fMain.setNamaKota(lblKotaTujuan.getText());
//            }
//            dispose();
//        }
        if(JOptionPane.showConfirmDialog(this, "Ubah kota?", "Confirm", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            Utama.sKodeKota=lstKodeKota.get(cmbKota.getSelectedIndex()).toString();
            Utama.sNamaKota=cmbKota.getSelectedItem().toString();
            fMain.setKodeKota(lstKodeKota.get(cmbKota.getSelectedIndex()).toString());
            fMain.setNamaKota(cmbKota.getSelectedItem().toString());
            fMain.sKotaSingkat=lstKodeKota.get(cmbKota.getSelectedIndex()).toString();

            dispose();
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmbKotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbKotaKeyPressed
//        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
//            LogMasuk();
//        }
}//GEN-LAST:event_cmbKotaKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgGantiKota dialog = new DlgGantiKota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbKota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKotaRecent;
    // End of variables declaration//GEN-END:variables
    
}
