/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgItemNota.java
 *
 * Created on 05 Nov 10, 5:38:11
 */

package tpjkeuangan;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cak-ust
 */
public class DlgItemNota extends javax.swing.JDialog {
    private Connection conn;

    /** Creates new form DlgItemNota */
    public DlgItemNota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblItem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int iRow=tblItem.getSelectedRow();
                btnDeleteItem.setEnabled(iRow>=0);
                btnUpdateItem.setEnabled(iRow>=0);
                if(iRow<0) return;
                jTextArea1.setText(tblItem.getValueAt(iRow, 0).toString());
            }
        });

        tblSatuan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int iRow=tblSatuan.getSelectedRow();
                btnDeleteItem1.setEnabled(iRow>=0);
                btnUpdateItem1.setEnabled(iRow>=0);
                if(iRow<0) return;
                txtSatuan.setText(tblSatuan.getValueAt(iRow, 0).toString());
                txtKetSatuan.setText(tblSatuan.getValueAt(iRow, 1).toString());
            }
        });

        tblSatuan.getColumn("Ket. Satuan").setPreferredWidth(300);
    }

    public void setConn(Connection con){
        this.conn=con;
    }

    private void udfInitForm(){
        try{
            ResultSet rs=conn.createStatement().executeQuery("select item_trx from nota_item_trx order by 1 ");
            ((javax.swing.table.DefaultTableModel)tblItem.getModel()).setNumRows(0);
            while(rs.next()){
                ((javax.swing.table.DefaultTableModel)tblItem.getModel()).addRow(new Object[]{rs.getString(1)});
            }
            rs.close();
            if(tblItem.getRowCount()>0)
                tblItem.setRowSelectionInterval(0, 0);

            rs=conn.createStatement().executeQuery("select coalesce(satuan,'') as satuan, coalesce(ket_satuan,'') as ket_satuan from nota_satuan order by 1, 2");
            ((javax.swing.table.DefaultTableModel)tblSatuan.getModel()).setNumRows(0);
            while(rs.next()){
                ((javax.swing.table.DefaultTableModel)tblSatuan.getModel()).addRow(new Object[]{
                    rs.getString(1),rs.getString(2)
                });
            }
            rs.close();
            if(tblSatuan.getRowCount()>0)
                tblSatuan.setRowSelectionInterval(0, 0);
            rs.close();

        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnDeleteItem = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        txtSatuan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSatuan = new javax.swing.JTable();
        btnUpdateItem1 = new javax.swing.JButton();
        btnDeleteItem1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKetSatuan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeleteItem.setText("Delete");
        btnDeleteItem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDeleteItem.setName("btnDeleteItem"); // NOI18N
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 70, -1));

        btnUpdateItem.setText("Update");
        btnUpdateItem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnUpdateItem.setName("btnUpdateItem"); // NOI18N
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 70, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item List"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItem.setName("tblItem"); // NOI18N
        tblItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblItemKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 640, 230));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 480, 60));

        jTabbedPane1.addTab("Item Transaksi", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSatuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSatuan.setName("txtSatuan"); // NOI18N
        jPanel2.add(txtSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, 20));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        tblSatuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Satuan", "Ket. Satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSatuan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblSatuan.setName("tblSatuan"); // NOI18N
        tblSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSatuanKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblSatuan);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 640, 260));

        btnUpdateItem1.setText("Update");
        btnUpdateItem1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnUpdateItem1.setName("btnUpdateItem1"); // NOI18N
        btnUpdateItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItem1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdateItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 70, -1));

        btnDeleteItem1.setText("Delete");
        btnDeleteItem1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDeleteItem1.setName("btnDeleteItem1"); // NOI18N
        btnDeleteItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItem1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 70, -1));

        jLabel2.setText("Satuan : ");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 20));

        jLabel3.setText("Ket. Satuan : ");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, 20));

        txtKetSatuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtKetSatuan.setName("txtKetSatuan"); // NOI18N
        jPanel2.add(txtKetSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 180, 20));

        jTabbedPane1.addTab("Satuan", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 670, 330));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     Maintenance Item Nota");
        jLabel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 710, 40));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/exit_32.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 90, 30));

        btnClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/refresh_32.png"))); // NOI18N
        btnClose1.setText("Refresh");
        btnClose1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnClose1.setName("btnClose1"); // NOI18N
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 90, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-716)/2, (screenSize.height-474)/2, 716, 474);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        udfInitForm();
    }//GEN-LAST:event_formWindowOpened

    private void tblItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblItemKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DELETE)
            udfDeleteItem();
    }//GEN-LAST:event_tblItemKeyPressed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        udfInitForm();
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        udfDeleteItem();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
        udfUpdateItem();
    }//GEN-LAST:event_btnUpdateItemActionPerformed

    private void tblSatuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSatuanKeyPressed
        udfDeleteSatuan();
    }//GEN-LAST:event_tblSatuanKeyPressed

    private void btnUpdateItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItem1ActionPerformed
        udfUpdateSatuan();
    }//GEN-LAST:event_btnUpdateItem1ActionPerformed

    private void btnDeleteItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItem1ActionPerformed
        udfDeleteSatuan();
    }//GEN-LAST:event_btnDeleteItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgItemNota dialog = new DlgItemNota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDeleteItem1;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JButton btnUpdateItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblSatuan;
    private javax.swing.JTextField txtKetSatuan;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables

    private void udfDeleteItem() {
        if(JOptionPane.showConfirmDialog(this, "Anda yakin untuk menghapus keterangan nota ini?", "Confirm", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            if(tblItem.getSelectedRow()>=0){
                int iRow[]= tblItem.getSelectedRows();
                int rowPalingAtas=iRow[0];
                for (int a=0; a<iRow.length; a++){
                    try{
                        conn.createStatement().executeUpdate("delete from nota_item_trx where item_trx='"+tblItem.getValueAt(tblItem.getSelectedRow(), 0).toString()+"'");
                    }catch(SQLException se){
                        JOptionPane.showMessageDialog(this, se.getMessage());
                    }
                    ((DefaultTableModel)tblItem.getModel()).removeRow(tblItem.getSelectedRow());

                }

                if(tblItem.getRowCount()>0 && rowPalingAtas<tblItem.getRowCount()){
                    tblItem.setRowSelectionInterval(rowPalingAtas, rowPalingAtas);
                }else{
                    if(tblItem.getRowCount()>0)
                        tblItem.setRowSelectionInterval(rowPalingAtas-1, rowPalingAtas-1);
                    else
                        jTextArea1.requestFocus();
                }
                if(tblItem.getSelectedRow()>=0)
                    tblItem.changeSelection(tblItem.getSelectedRow(), 0, false, false);
            }
        }
    }

    private void udfUpdateItem(){
        int iRow=tblItem.getSelectedRow();
        if(iRow<0) return;
        boolean isNew=true;
        try{
            ResultSet rs=conn.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_UPDATABLE)
                    .executeQuery("select * from nota_item_trx where item_trx='"+tblItem.getValueAt(iRow, 0).toString()+"'");
            if(rs.next())
                isNew=false;
            else
                rs.moveToInsertRow();

            rs.updateString("item_trx", jTextArea1.getText());

            if(isNew)
                rs.insertRow();
            else
                rs.updateRow();

            ((DefaultTableModel)tblItem.getModel()).setValueAt(jTextArea1.getText(), iRow, 0);
        }catch(SQLException se){

        }
    }

    private void udfDeleteSatuan() {
        if(JOptionPane.showConfirmDialog(this, "Anda yakin untuk menghapus Satuan ini?", "Confirm", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            if(tblSatuan.getSelectedRow()>=0){
                int iRow[]= tblSatuan.getSelectedRows();
                int rowPalingAtas=iRow[0];
                for (int a=0; a<iRow.length; a++){
                    try{
                        conn.createStatement().executeUpdate("delete from nota_satuan where " +
                                "coalesce(satuan,'')='"+tblSatuan.getValueAt(tblSatuan.getSelectedRow(), 0).toString()+"' and " +
                                "coalesce(ket_satuan,'')='"+tblSatuan.getValueAt(tblSatuan.getSelectedRow(), 1).toString()+"'");
                    }catch(SQLException se){
                        JOptionPane.showMessageDialog(this, se.getMessage());
                    }
                    ((DefaultTableModel)tblSatuan.getModel()).removeRow(tblSatuan.getSelectedRow());

                }

                if(tblSatuan.getRowCount()>0 && rowPalingAtas<tblSatuan.getRowCount()){
                    tblSatuan.setRowSelectionInterval(rowPalingAtas, rowPalingAtas);
                }else{
                    if(tblSatuan.getRowCount()>0)
                        tblSatuan.setRowSelectionInterval(rowPalingAtas-1, rowPalingAtas-1);
                    else
                        jTextArea1.requestFocus();
                }
                if(tblSatuan.getSelectedRow()>=0)
                    tblSatuan.changeSelection(tblSatuan.getSelectedRow(), 0, false, false);
            }
        }
    }

    private void udfUpdateSatuan(){
        int iRow=tblSatuan.getSelectedRow();
        if(iRow<0) return;
        boolean isNew=true;
        try{
            ResultSet rs=conn.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_UPDATABLE)
                    .executeQuery("select * from nota_satuan where " +
                                "coalesce(satuan,'')='"+tblSatuan.getValueAt(tblSatuan.getSelectedRow(), 0).toString()+"' and " +
                                "coalesce(ket_satuan,'')='"+tblSatuan.getValueAt(tblSatuan.getSelectedRow(), 1).toString()+"'");
            if(rs.next())
                isNew=false;
            else
                rs.moveToInsertRow();

            rs.updateString("satuan", txtSatuan.getText());
            rs.updateString("ket_satuan", txtKetSatuan.getText());

            if(isNew)
                rs.insertRow();
            else
                rs.updateRow();

            ((DefaultTableModel)tblSatuan.getModel()).setValueAt(txtSatuan.getText(), iRow, 0);
            ((DefaultTableModel)tblSatuan.getModel()).setValueAt(txtKetSatuan.getText(), iRow, 1);
        }catch(SQLException se){

        }
    }
}
