/*
 * FrmListPembayaran.java
 *
 * Created on August 8, 2008, 7:19 AM
 */

package tpjkeuangan;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import main.GeneralFunction;

/**
 *
 * @author  oestadho
 */
public class FrmListPembayaran extends javax.swing.JInternalFrame {
    ListRsbm lst;
    Connection conn;
    SimpleDateFormat fmtYMD=new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel myModel;
    private String sUserName;
    Utama fUtama;
    JDesktopPane jDesktop;
    private GeneralFunction fn=new GeneralFunction();
    
    /** Creates new form FrmListPembayaran */
    public FrmListPembayaran() {
        initComponents();
    }

    void setDesktop(JDesktopPane jd){
        jDesktop=jd;
    }
    
    void setConn(Connection con){
        conn=con;
        fn.setConn(conn);
    }

    void setUserName(String sUserName) {
        this.sUserName=sUserName;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenerimaan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelPerTanggal = new javax.swing.JPanel();
        lblTglAwal = new javax.swing.JLabel();
        jDateAwal = new org.jdesktop.swingx.JXDatePicker();
        lblTglAkhir = new javax.swing.JLabel();
        jDateAkhir = new org.jdesktop.swingx.JXDatePicker();
        jLabel24 = new javax.swing.JLabel();
        txtJenisBayar = new javax.swing.JTextField();
        lblJenisBayar = new javax.swing.JLabel();
        panelKapal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtKapal = new javax.swing.JTextField();
        lblKotaTujuan = new javax.swing.JLabel();
        lblKapal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSerialKapal = new javax.swing.JLabel();
        lblTglBerangkat = new javax.swing.JLabel();
        panelKota = new javax.swing.JPanel();
        txtKota = new javax.swing.JTextField();
        lblKota = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelCustomer = new javax.swing.JPanel();
        txtCustomer = new javax.swing.JTextField();
        lblCustomerTujuan = new javax.swing.JLabel();
        optToko = new javax.swing.JRadioButton();
        optCustomer = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Daftar Pembayaran Customer");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblPenerimaan.setAutoCreateRowSorter(true);
        tblPenerimaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Alat pembayaran", "Customer", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPenerimaan.setName("tblPenerimaan"); // NOI18N
        tblPenerimaan.getTableHeader().setReorderingAllowed(false);
        tblPenerimaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenerimaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenerimaan);
        tblPenerimaan.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblPenerimaan.getColumnModel().getColumn(1).setPreferredWidth(10);
        tblPenerimaan.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblPenerimaan.getColumnModel().getColumn(4).setPreferredWidth(10);

        jButton1.setText("Show");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Detail");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.CardLayout());

        panelPerTanggal.setName("panelPerTanggal"); // NOI18N

        lblTglAwal.setText("Dari");
        lblTglAwal.setName("lblTglAwal"); // NOI18N

        jDateAwal.setName("jDateAwal"); // NOI18N

        lblTglAkhir.setText("Sampai");
        lblTglAkhir.setName("lblTglAkhir"); // NOI18N

        jDateAkhir.setName("jDateAkhir"); // NOI18N

        jLabel24.setText("Jenis");
        jLabel24.setName("jLabel24"); // NOI18N

        txtJenisBayar.setFont(new java.awt.Font("Dialog", 0, 12));
        txtJenisBayar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtJenisBayar.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtJenisBayar.setName("txtJenisBayar"); // NOI18N
        txtJenisBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJenisBayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJenisBayarKeyReleased(evt);
            }
        });

        lblJenisBayar.setFont(new java.awt.Font("Dialog", 0, 12));
        lblJenisBayar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblJenisBayar.setName("lblJenisBayar"); // NOI18N

        javax.swing.GroupLayout panelPerTanggalLayout = new javax.swing.GroupLayout(panelPerTanggal);
        panelPerTanggal.setLayout(panelPerTanggalLayout);
        panelPerTanggalLayout.setHorizontalGroup(
            panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerTanggalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTglAwal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerTanggalLayout.createSequentialGroup()
                        .addComponent(jDateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerTanggalLayout.createSequentialGroup()
                        .addComponent(txtJenisBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJenisBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPerTanggalLayout.setVerticalGroup(
            panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerTanggalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPerTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJenisBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblJenisBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel1.add(panelPerTanggal, "card2");

        panelKapal.setName("panelKapal"); // NOI18N
        panelKapal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("KAPAL");
        jLabel8.setName("jLabel8"); // NOI18N
        panelKapal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 80, -1));

        txtKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        txtKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtKapal.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtKapal.setName("txtKapal"); // NOI18N
        txtKapal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKapalFocusLost(evt);
            }
        });
        txtKapal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKapalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKapalKeyReleased(evt);
            }
        });
        panelKapal.add(txtKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 6, 60, 24));

        lblKotaTujuan.setBackground(new java.awt.Color(255, 255, 255));
        lblKotaTujuan.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKotaTujuan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKotaTujuan.setName("lblKotaTujuan"); // NOI18N
        lblKotaTujuan.setOpaque(true);
        panelKapal.add(lblKotaTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 32, 240, 24));

        lblKapal.setBackground(new java.awt.Color(255, 255, 255));
        lblKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKapal.setName("lblKapal"); // NOI18N
        lblKapal.setOpaque(true);
        panelKapal.add(lblKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 6, 400, 24));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Tgl. Berangkat");
        jLabel12.setName("jLabel12"); // NOI18N
        panelKapal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 34, 100, 20));

        lblSerialKapal.setText("0");
        lblSerialKapal.setName("lblSerialKapal"); // NOI18N
        panelKapal.add(lblSerialKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 37, 50, -1));

        lblTglBerangkat.setBackground(new java.awt.Color(255, 255, 255));
        lblTglBerangkat.setFont(new java.awt.Font("Dialog", 0, 12));
        lblTglBerangkat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblTglBerangkat.setName("lblTglBerangkat"); // NOI18N
        lblTglBerangkat.setOpaque(true);
        panelKapal.add(lblTglBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 32, 90, 24));

        jPanel1.add(panelKapal, "card3");

        panelKota.setName("panelKota"); // NOI18N
        panelKota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKota.setFont(new java.awt.Font("Dialog", 0, 12));
        txtKota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtKota.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtKota.setName("txtKota"); // NOI18N
        txtKota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKotaFocusLost(evt);
            }
        });
        txtKota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKotaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKotaKeyReleased(evt);
            }
        });
        panelKota.add(txtKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, 24));

        lblKota.setBackground(new java.awt.Color(255, 255, 255));
        lblKota.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKota.setName("lblKota"); // NOI18N
        lblKota.setOpaque(true);
        panelKota.add(lblKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 400, 24));

        jLabel1.setText("Kota");
        jLabel1.setName("jLabel1"); // NOI18N
        panelKota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 20));

        jPanel1.add(panelKota, "card4");

        panelCustomer.setName("panelCustomer"); // NOI18N
        panelCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustomer.setFont(new java.awt.Font("Dialog", 0, 12));
        txtCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCustomer.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCustomer.setName("txtCustomer"); // NOI18N
        txtCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerFocusLost(evt);
            }
        });
        txtCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerKeyReleased(evt);
            }
        });
        panelCustomer.add(txtCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 24));

        lblCustomerTujuan.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomerTujuan.setFont(new java.awt.Font("Dialog", 0, 12));
        lblCustomerTujuan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblCustomerTujuan.setName("lblCustomerTujuan"); // NOI18N
        lblCustomerTujuan.setOpaque(true);
        panelCustomer.add(lblCustomerTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 400, 24));

        buttonGroup1.add(optToko);
        optToko.setText("Toko pengirim");
        optToko.setName("optToko"); // NOI18N
        panelCustomer.add(optToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 110, -1));

        buttonGroup1.add(optCustomer);
        optCustomer.setSelected(true);
        optCustomer.setText("Customer tujuan");
        optCustomer.setName("optCustomer"); // NOI18N
        panelCustomer.add(optCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jPanel1.add(panelCustomer, "card4");

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Per tanggal pembayaran", "Per Kapal Berangkat", "Per Kota", "Per Customer" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jList1.setSelectedIndex(0);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 687, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 587, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tblPenerimaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenerimaanMouseClicked

}//GEN-LAST:event_tblPenerimaanMouseClicked

private void txtJenisBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJenisBayarKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtJenisBayarKeyPressed

private void txtJenisBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJenisBayarKeyReleased
    try {
        String sCari = txtJenisBayar.getText();
        switch(evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_ENTER : {
                if (lst.isVisible()){
                    Object[] obj = lst.getOResult();
                    if (obj.length > 0) {
                        txtJenisBayar.setText(obj[0].toString());
                        lblJenisBayar.setText(obj[1].toString());
                        //lblAlamatToko.setText(obj[2].toString());
                        lst.setVisible(false);
                    }
                }
                break;
            }
            case java.awt.event.KeyEvent.VK_DELETE: {
                lst.setFocusable(true);
                lst.requestFocus();

                break;
            }
            case java.awt.event.KeyEvent.VK_ESCAPE: {
                lst.setVisible(false);
                txtJenisBayar.setText("");
                lblJenisBayar.setText("");
            }
            case java.awt.event.KeyEvent.VK_DOWN: {
                if (lst.isVisible()){

                    lst.setFocusableWindowState(true);
                    lst.setVisible(true);
                    lst.requestFocus();
                }
                break;
            }
            default : {
                if(!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")){
//                        if(txtSupplier.getText().trim().equalsIgnoreCase("")){
//                            JOptionPane.showMessageDialog(this, "Silakan isi supplier terlebih dulu!");
//                            txtSupplier.requestFocus();
//                            return;
//                        }   

                    String sQry="select coalesce(kode, '') as kode, coalesce(alat_pembayaran,'') as Jenis_pembayaran " +
                            "from nota_alat_pembayaran where (coalesce(kode, '')||coalesce(alat_pembayaran,'')) " +
                            "iLike '%"+sCari+"%' order by 2";

                    System.out.println(sQry);
                    lst.setSQuery(sQry);

                    lst.setBounds(this.getX()+this.jPanel1.getX()+ this.txtJenisBayar.getX()+Utama.iLeft+17, 
                            this.getY()+this.jPanel1.getY()+this.txtJenisBayar.getY() + txtJenisBayar.getHeight()+Utama.iTop+77, 
                            txtJenisBayar.getWidth()+lblJenisBayar.getWidth()+5,
                            150);
                    lst.setFocusableWindowState(false);
                    lst.setTxtCari(txtJenisBayar);
                    lst.setLblDes(new javax.swing.JLabel[]{lblJenisBayar});
                    lst.setColWidth(0, txtJenisBayar.getWidth());
                    lst.setColWidth(1, lblJenisBayar.getWidth());
                    if(lst.getIRowCount()>0){
                        lst.setVisible(true);
                        requestFocusInWindow();
                        txtJenisBayar.requestFocus();
                    } else{
                        txtJenisBayar.setText("");
                        lblJenisBayar.setText("");
                        lst.setVisible(false);
                        txtJenisBayar.requestFocus();
                    }
                }
                break;
            }
        }
    } catch (SQLException se) {System.out.println(se.getMessage());}
}//GEN-LAST:event_txtJenisBayarKeyReleased

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String sCriteria="";
    switch (jList1.getSelectedIndex()){
        case 0:{ //Per tanggal nota
            sCriteria=  "Where alat_bayar like '"+txtJenisBayar.getText()+"%' " +
                        "and to_Char(n.tanggal,'yyyy-MM-dd')>='"+fmtYMD.format(jDateAwal.getDate())+"' " +
                        "and to_Char(n.tanggal,'yyyy-MM-dd')<='"+fmtYMD.format(jDateAkhir.getDate())+"' ";
            break;
        }
        case 1:{ //Per kapal berangkat
            sCriteria=  "Where n.seri_kapal="+lblSerialKapal.getText()+" ";
            break;
        }
        case 2:{ //Per kota
            sCriteria=  "Where (coalesce(c.kota,'')||coalesce(t.kota,'')) like '"+txtKota.getText()+"' ";
            break;
        }
        case 3:{ //Per customer
            sCriteria=  "Where n.kode_cust Like '"+txtCustomer.getText()+"' and tagihan_per = '"+(optCustomer.isSelected()? "T" :"P")+"'";
            break;
        }
        default :{
             sCriteria=  "Where alat_bayar like '"+txtJenisBayar.getText()+"%' " +
                        "and to_Char(n.tanggal,'yyyy-MM-dd')>='"+fmtYMD.format(jDateAwal.getDate())+"' " +
                        "and to_Char(n.tanggal,'yyyy-MM-dd')<='"+fmtYMD.format(jDateAkhir.getDate())+"' ";
             break;
        }
    }
    
    String sQry="select d.no_bayar, to_char(tanggal, 'dd-MM-yyyy') as tanggal, coalesce(alat_pembayaran,'') as alat_pembayaran, " +
            "case when to_tujuan=true then coalesce(c.nama,'') else coalesce(toko.nama,'') end as customer, " +
            "sum(coalesce(jumlah,0)- coalesce(diskon,0)+coalesce(klem,0)) as jml_bayar " +
            "from nota_pembayaran n " +
            "left join nota_pembayaran_detail d on d.no_bayar=n.no_bayar " +
            "left join nota_alat_pembayaran ap on ap.kode=alat_bayar " +
            "left join customer c on c.kode_cust=n.kode_cust " +
            "left join toko on toko.kode_toko=n.kode_cust " +
            "left join nota on nota.no_nota=d.no_nota " +
            sCriteria +
            "group by d.no_bayar, to_char(tanggal, 'dd-MM-yyyy'), coalesce(alat_pembayaran,'') , " +
            "case when to_tujuan=true then coalesce(c.nama,'') else coalesce(toko.nama,'') end order by d.no_bayar";
    
    System.out.println(sQry);
    
    try{
        ResultSet rs=conn.createStatement().executeQuery(sQry);
        myModel.setNumRows(0);
        while(rs.next()){
            myModel.addRow(new Object[]{
                rs.getString("no_bayar"),
                rs.getString("tanggal"),
                rs.getString("alat_pembayaran"),
                rs.getString("customer"),
                rs.getFloat("jml_bayar")
            });
        }
        
    }catch(SQLException se){
        System.err.println("jButton1ActionPerformed "+se.getMessage());
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    lst = new ListRsbm();
    lst.setVisible(false);
    lst.setSize(500, 200);
    lst.con = conn;

    myModel=(DefaultTableModel)tblPenerimaan.getModel();
    myModel.setNumRows(0);
}//GEN-LAST:event_formInternalFrameOpened

private void txtKapalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKapalFocusLost

}//GEN-LAST:event_txtKapalFocusLost

private void txtKapalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKapalKeyPressed

}//GEN-LAST:event_txtKapalKeyPressed

private void txtKapalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKapalKeyReleased
String sQry="select tj.kode_kapal, nama_kapal , to_Char(tgl_berangkat, 'dd-MM-yyyy') as tgl_berangkat, " +
                        "coalesce(nama_kota,'') as kota_tujuan, serial_kode " +
                        "from nota_kapal_tujuan tj " +
                        "inner join kapal on kapal.kode_kapal=tj.kode_kapal " +
                        "left join kota on kode_kota=kota_tujuan " +
                        "where (tj.kode_kapal||nama_kapal||coalesce(nama_kota,'') ) iLike '%"+txtKapal.getText()+"%' and active=true limit 100";

fn.lookup(evt, new Object[]{lblKapal, lblTglBerangkat, lblKotaTujuan, lblSerialKapal}, 
        sQry, txtKapal.getWidth()+lblKapal.getWidth()+100, 200);
}//GEN-LAST:event_txtKapalKeyReleased

private void txtCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_txtCustomerFocusLost

private void txtCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtCustomerKeyPressed

private void txtCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerKeyReleased
    try {
            String sCari = txtCustomer.getText();
            switch(evt.getKeyCode()) {
                
                case java.awt.event.KeyEvent.VK_ENTER : {
                    if (lst.isVisible()){
                        Object[] obj = lst.getOResult();
                        if (obj.length > 0) {
                            txtCustomer.setText(obj[0].toString());
                            lblCustomerTujuan.setText(obj[1].toString());
                            lst.setVisible(false);
                        }
                    }
                    break;
                }
                case java.awt.event.KeyEvent.VK_DELETE: {
                    lst.setFocusable(true);
                    lst.requestFocus();
                    
                    break;
                }
                 case java.awt.event.KeyEvent.VK_ESCAPE: {
                    lst.setVisible(false);
                    txtCustomer.setText("");
                    lblCustomerTujuan.setText("");
                    txtCustomer.requestFocus();
                    break;
                }
                case java.awt.event.KeyEvent.VK_DOWN: {
                    if (lst.isVisible()){
                        lst.setFocusableWindowState(true);
                        lst.setVisible(true);
                        lst.requestFocus();
                    }
                    break;
                }
                default : {
                    if(!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")){
                        //sQry=getQuery();
                        
                        ///System.out.println(sQry);
                        lst.setSQuery(getQuery());
                        
                        lst.setBounds(Utama.iLeft+ this.getX()+this.jPanel1.getX()+ panelCustomer.getX()+ this.txtCustomer.getX()+17, 
                                Utama.iTop+ this.getY()+this.jPanel1.getY()+ panelCustomer.getY() + this.txtCustomer.getY()+  txtCustomer.getHeight()+77, 
                                txtCustomer.getWidth()+lblCustomerTujuan.getWidth(),
                                150);
                        lst.setFocusableWindowState(false);
                        lst.setTxtCari(txtCustomer);
                        lst.setLblDes(new javax.swing.JLabel[]{lblCustomerTujuan});
                        lst.setColWidth(0, txtCustomer.getWidth());
                        lst.setColWidth(1, 250);
                        
                        if(lst.getIRowCount()>0){
                            lst.setVisible(true);
                            requestFocusInWindow();
                            txtCustomer.requestFocus();
                        } else{
                            lst.setVisible(false);
                            txtCustomer.setText("");
                            lblCustomerTujuan.setText("");
                            
                            txtCustomer.requestFocus();
                        }
                    }
                    break;
                }
            }
        } catch (SQLException se) {System.out.println(se.getMessage());}
}//GEN-LAST:event_txtCustomerKeyReleased

private void txtKotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKotaFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_txtKotaFocusLost

private void txtKotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKotaKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtKotaKeyPressed

private void txtKotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKotaKeyReleased
    try {
        switch(evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_ENTER : {
                if (lst.isVisible()){
                    Object[] obj = lst.getOResult();
                    if (obj.length > 0) {
                        txtKota.setText(obj[0].toString());
                        lblKota.setText(obj[1].toString());
                        lst.setVisible(false);
                    }
                }
                break;
            }
            case java.awt.event.KeyEvent.VK_DELETE: {
                lst.setFocusable(true);
                lst.requestFocus();

                break;
            }
             case java.awt.event.KeyEvent.VK_ESCAPE: {
                lst.setVisible(false);
                txtKota.setText("");
                lblKota.setText("");
                txtKota.requestFocus();
                break;
            }
            case java.awt.event.KeyEvent.VK_DOWN: {
                if (lst.isVisible()){
                    lst.setFocusableWindowState(true);
                    lst.setVisible(true);
                    lst.requestFocus();
                }
                break;
            }
            default : {
                if(!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")){
                    String sQry="select kode_kota as kode, coalesce(nama_kota,'') as nama_kota " +
                            "from kota where upper(kode_kota||coalesce(nama_kota,'') ) " +
                            "ilike upper('%"+txtKota.getText()+"%') order by 2";

                    System.out.println(sQry);
                    lst.setSQuery(sQry);

                    lst.setBounds(Utama.iLeft+ this.getX()+this.jPanel1.getX()+ panelKota.getX()+ this.txtKota.getX()+17, 
                            Utama.iTop + this.getY()+this.jPanel1.getY()+ panelKota.getY() + this.txtKota.getY()+  txtKota.getHeight()+77, 
                            txtKota.getWidth()+lblKota.getWidth(),
                            150);
                    lst.setFocusableWindowState(false);
                    lst.setTxtCari(txtKota);
                    lst.setLblDes(new javax.swing.JLabel[]{lblKota});
                    lst.setColWidth(0, txtKota.getWidth());
                    lst.setColWidth(1, 250);

                    if(lst.getIRowCount()>0){
                        lst.setVisible(true);
                        requestFocusInWindow();
                        txtKota.requestFocus();
                    } else{
                        lst.setVisible(false);
                        txtKota.setText("");
                        lblKota.setText("");

                        txtKota.requestFocus();
                    }
                }
                break;
            }
        }
    } catch (SQLException se) {System.out.println(se.getMessage());}
}//GEN-LAST:event_txtKotaKeyReleased

private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
    panelPerTanggal.setVisible(false);
    panelKapal.setVisible(false);
    panelKota.setVisible(false);
    panelCustomer.setVisible(false);
    lst.setVisible(false);
    
    switch(jList1.getSelectedIndex()){
        case 0:{//Per kontainer
            panelPerTanggal.setVisible(true);
            break;
        }

        case 1 :{//Per Kapal
            panelKapal.setVisible(true);
            break;
        }

        case 2:{//Per Kota Tujuan
            panelKota.setVisible(true);
            break;
        }

        case 3:{//Per Emkl
            panelCustomer.setVisible(true);
            break;
        }

        default:{
            panelPerTanggal.setVisible(true);
            break;
        }
    }
}//GEN-LAST:event_jList1ValueChanged

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(tblPenerimaan.getSelectedRow()>=0){
        FrmPembayaran d1=new FrmPembayaran();
        d1.setUserName(sUserName);
        d1.setConn(conn);
        d1.setKoreksi(true);
        d1.setKodeBayar(tblPenerimaan.getValueAt(tblPenerimaan.getSelectedRow(), 0).toString());
        d1.setTitle("Koreksi pembayaran nota : "+tblPenerimaan.getValueAt(tblPenerimaan.getSelectedRow(), 0).toString());
        d1.udfLoadPembayaran();
        jDesktop.add(d1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        d1.setVisible(true);
        try{
            d1.setBounds(this.getX(), this.getY(), d1.getWidth(), d1.getHeight());
            d1.setSelected(true);
        } catch(PropertyVetoException PO){
        }
        
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton3ActionPerformed

private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
    Utama.isListBayar=false;
}//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private org.jdesktop.swingx.JXDatePicker jDateAkhir;
    private org.jdesktop.swingx.JXDatePicker jDateAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomerTujuan;
    private javax.swing.JLabel lblJenisBayar;
    private javax.swing.JLabel lblKapal;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblKotaTujuan;
    private javax.swing.JLabel lblSerialKapal;
    private javax.swing.JLabel lblTglAkhir;
    private javax.swing.JLabel lblTglAwal;
    private javax.swing.JLabel lblTglBerangkat;
    private javax.swing.JRadioButton optCustomer;
    private javax.swing.JRadioButton optToko;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JPanel panelKapal;
    private javax.swing.JPanel panelKota;
    private javax.swing.JPanel panelPerTanggal;
    private javax.swing.JTable tblPenerimaan;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtJenisBayar;
    private javax.swing.JTextField txtKapal;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables

    private String getQuery(){
        String sQry="";
        if(optCustomer.isSelected()){
            sQry="select c.kode_cust as kode,  coalesce(c.nama,'') as toko, " +
                 "coalesce(c.nama,'') ||' ('|| gabung(merk.merk)||'), ' ||coalesce(nama_kota,'') as kepada " +
                 "from customer c inner join merk on c.kode_cust=merk.kode_cust " +
                 "left join kota on kota.kode_kota=c.kota " +
                 "where (coalesce(c.nama,'')||coalesce(merk.merk,'')||coalesce(nama_kota,'')) iLike '%"+txtCustomer.getText()+"%' " +
                 "and c.kota like '%"+Utama.sKodeKota+"%' " +
                 "group by c.kode_cust, coalesce(c.nama,''), coalesce(nama_kota,'') " +
                 "order by coalesce(c.nama,'')";
                    
            return sQry;
        }
        
        if(optToko.isSelected()){
            sQry=   "select kode_toko, coalesce(nama,'') as nama, coalesce(nama,'') as kepada " +
                    "from toko where coalesce(nama,'') iLike '%"+txtCustomer.getText()+"%' order by coalesce(nama,'') ";
            
            return sQry;
        }
        
        return sQry;
    }
    
    
}
