/*
 * FrmTrxBayar.java
 *
 * Created on May 7, 2008, 6:03 AM
 */

package tpjkeuangan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  oestadho
 */
public class FrmNotaBayarDetail extends javax.swing.JFrame {
    Statement stH, stD;
    ResultSet rsH, rsD;
    Connection conn;
    NumberFormat fmt=DecimalFormat.getInstance();
    DefaultTableModel myModel;
    private String sCustomer;
    private String sUserName;
    
    
    /** Creates new form FrmTrxBayar */
    //public FrmTrxBayar() {
    public FrmNotaBayarDetail() {
    //public DlgNotaBayarDetail(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        
        myModel=(DefaultTableModel)jTable1.getModel();
        jTable1.setModel(myModel);
    }

    void setConn(Connection conn) {
        this.conn=conn;
    }

    void setNoNota(String s) {
        txtNota.setText(s);
    }

    void setUserName(String sUser) {
        this.sUserName=sUser;
    }
    
    private void udfBlank(){
        lblKepada.setText("");
        lblKapal.setText("");
        lblJmlNota.setText("0");
        lblTglNota.setText("");
        myModel.setNumRows(0);
        
        lblTotalBayar.setText("0");
        lblTotalKlem.setText("0");
        
    }
    
    private float udfGetFloat(String sNum){
    float hsl=0;
    if(!sNum.trim().equalsIgnoreCase("")){
        try{
            hsl=Float.valueOf(sNum.replace(",", ""));
        }catch(NumberFormatException ne){
            hsl=0;
        }catch(IllegalArgumentException i){
            hsl=0;
        }
    }
    return hsl;
  }
    
    private void udfLoadDetailTagihan(){
        udfBlank();
        String sH="select nota.no_nota, to_char(tgl_nota, 'dd/MM/yyyy') as tgl_nota, kepada, customer," +
                "coalesce(nama_kapal,'')||' Tgl. Berangkat '||coalesce(to_char(tgl_berangkat, 'dd-MM-yyyy'), '') as kapal," +
                "fn_nota_grand_total(nota.no_nota) as total_tagihan " +
                "from nota " +
                "inner join nota_detail d using(no_nota) " +
                "left join nota_kapal_tujuan tj on tj.serial_kode=nota.seri_kapal " +
                "left join kapal on kapal.kode_kapal=tj.kode_kapal " +
                "where nota.no_nota='"+txtNota.getText()+"'  " +
                "group by nota.no_nota, customer, to_char(tgl_nota, 'dd/MM/yyyy'), kepada, coalesce(nama_kapal,'')||' Tgl. Berangkat '||coalesce(to_char(tgl_berangkat, 'dd-MM-yyyy'), '') " ;
        
        String sD="select dp.no_bayar, to_char(tanggal, 'dd-MM-yyyy') as tanggal, ap.alat_pembayaran, memo, coalesce(jumlah, 0) as jml_bayar, " +
                "coalesce(klem, 0) as jml_klem " +
                "from nota_pembayaran pb " +
                "inner join nota_pembayaran_detail dp on dp.no_bayar=pb.no_bayar " +
                "left join nota_alat_pembayaran ap on ap.kode=pb.alat_bayar where no_nota='"+txtNota.getText()+"' order by 1";
        
        
        try {
            stH = conn.createStatement();
            rsH=stH.executeQuery(sH);
            
            if(rsH.next()){
                lblKepada.setText(rsH.getString("kepada"));
                lblKapal.setText(rsH.getString("kapal"));
                lblTglNota.setText(rsH.getString("tgl_nota"));
                lblJmlNota.setText(fmt.format(rsH.getFloat("total_tagihan")));
                sCustomer=rsH.getString("customer");
            }
            
            stD=conn.createStatement();
            rsD=stD.executeQuery(sD);
            
            myModel.setNumRows(0);
            
            int i=1;
            while(rsD.next()){
                myModel.addRow(new Object[]{
                    i,
                    rsD.getString("no_bayar"),
                    rsD.getString("tanggal"),
                    rsD.getString("alat_pembayaran"),
                    rsD.getString("memo"),
                    rsD.getFloat("jml_bayar"),
                    rsD.getFloat("jml_klem")
                });
                i++;
            }
            
            rsD.close(); stD.close();
            rsH.close(); stH.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmNotaBayarDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblKapal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblKepada = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTglNota = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblJmlNota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblTotalBayar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTotalKlem = new javax.swing.JLabel();
        btnKoreksi = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKapal.setBackground(new java.awt.Color(255, 255, 255));
        lblKapal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblKapal.setOpaque(true);
        jPanel2.add(lblKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 62, 700, 22));

        jLabel2.setText("No. Nota");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 70, 20));

        jLabel3.setText("Kepada");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 36, 70, 20));

        jLabel4.setText("Kapal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 70, 20));

        lblKepada.setBackground(new java.awt.Color(255, 255, 255));
        lblKepada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblKepada.setOpaque(true);
        jPanel2.add(lblKepada, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 37, 700, 22));

        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        txtNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNotaKeyReleased(evt);
            }
        });
        jPanel2.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 320, 22));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Tgl. Nota");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 29, 80, -1));

        lblTglNota.setBackground(new java.awt.Color(255, 255, 255));
        lblTglNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTglNota.setOpaque(true);
        jPanel3.add(lblTglNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 27, 120, 22));

        jLabel9.setText("Jml.Nota");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 31, 80, -1));

        lblJmlNota.setBackground(new java.awt.Color(255, 255, 255));
        lblJmlNota.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblJmlNota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJmlNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblJmlNota.setOpaque(true);
        jPanel3.add(lblJmlNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 29, 120, 22));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 90, 700, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, 800, 160));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No. Pembayaran", "Tgl. Bayar", "Alat Pembayaran", "Ket. Pembayaran", "Jumlah Bayar", "Klem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 232, 800, 180));

        jLabel11.setText("Jml. Terbayar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 421, 80, -1));

        lblTotalBayar.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalBayar.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTotalBayar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalBayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotalBayar.setOpaque(true);
        getContentPane().add(lblTotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 419, 120, 22));

        jLabel13.setText("Klem");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 420, 80, -1));

        lblTotalKlem.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalKlem.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTotalKlem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalKlem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotalKlem.setOpaque(true);
        getContentPane().add(lblTotalKlem, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 418, 120, 22));

        btnKoreksi.setText("Koreksi");
        btnKoreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoreksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnKoreksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 461, 110, 30));

        btnBatal.setText("Batal");
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 461, 110, 30));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 461, 110, 30));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 459, 110, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-827)/2, (screenSize.height-535)/2, 827, 535);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNotaActionPerformed

    private void btnKoreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoreksiActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnKoreksiActionPerformed

    private void txtNotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyReleased
        this.setTitle("No. Nota ~ "+txtNota.getText());
    }//GEN-LAST:event_txtNotaKeyReleased

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DlgBayarNota d2=new DlgBayarNota(JOptionPane.getFrameForComponent(this), false);
        d2.setConn(conn);
        d2.setTitle("No. Nota ~ "+txtNota.getText() );
        d2.setSisa( udfGetFloat(lblJmlNota.getText()) -
                    udfGetFloat(lblTotalBayar.getText())+udfGetFloat(lblTotalKlem.getText()) );
        
        d2.setUserName(sUserName);
        d2.setNota(txtNota.getText());
        d2.setCustomer(sCustomer);
        d2.setSrcModel(myModel);
        d2.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        udfLoadDetailTagihan();
    }//GEN-LAST:event_formWindowOpened
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgNotaBayarDetail dialog = new DlgNotaBayarDetail(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNotaBayarDetail().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnKoreksi;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblJmlNota;
    private javax.swing.JLabel lblKapal;
    private javax.swing.JLabel lblKepada;
    private javax.swing.JLabel lblTglNota;
    private javax.swing.JLabel lblTotalBayar;
    private javax.swing.JLabel lblTotalKlem;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
    
}
