/*
 * FrmRptRptNota.java
 *
 * Created on November 18, 2008, 6:06 AM
 */
package tpjkeuangan;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrator
 */
public class FrmRptNota extends javax.swing.JInternalFrame {
    private Connection conn;
    private String sKodeJenis = "";
    private String sUser = "";
    private DefaultListModel modelJenis, modelTrx;
    private ListRsbm lst;

    public void setCon(Connection con) {
        conn = con;
    }

    /**
     * Creates new form FrmRptRptNota
     */
    public FrmRptNota() {
        initComponents();

        jDateBerangkat1.setFormats("dd-MM-yyyy");
        jDateBerangkat2.setFormats("dd-MM-yyyy");
        jDateNota1.setFormats("dd-MM-yyyy");
        jDateNota2.setFormats("dd-MM-yyyy");
    }

    private void udfClear() {
        txtKotaTujuan.setText("");
        lblKota.setText("");
        lblPengirim.setText("");
        lblPengirim.setText("");
        lblToko.setText("");
        lblToko.setText("");
        lblKapal.setText("");
        lblKapal.setText("");
        lblTglBerangkat.setText("");
        lblSerialKapal.setText("0");
        txtMerk.setText("");
        txtItem.setText("");
        txtSatuan.setText("");
        txtKet.setText("");
        chkTglBerangkatSelected.setSelected(true);
        chkTglNotaSelected.setSelected(true);
        txtKotaTujuan.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtKotaTujuan = new javax.swing.JTextField();
        lblKota = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtKapal = new javax.swing.JTextField();
        lblTglBerangkat = new javax.swing.JLabel();
        lblKapal = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtToko = new javax.swing.JTextField();
        lblToko = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtPengirim = new javax.swing.JTextField();
        lblPengirim = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkTglBerangkatAll = new javax.swing.JRadioButton();
        chkTglBerangkatSelected = new javax.swing.JRadioButton();
        lblTglAwal = new javax.swing.JLabel();
        lblTglAkhir = new javax.swing.JLabel();
        jDateBerangkat1 = new org.jdesktop.swingx.JXDatePicker();
        jDateBerangkat2 = new org.jdesktop.swingx.JXDatePicker();
        jPanel3 = new javax.swing.JPanel();
        chkTglNotaAll = new javax.swing.JRadioButton();
        chkTglNotaSelected = new javax.swing.JRadioButton();
        lblTglAwal1 = new javax.swing.JLabel();
        lblTglAkhir1 = new javax.swing.JLabel();
        jDateNota1 = new org.jdesktop.swingx.JXDatePicker();
        jDateNota2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblSerialKapal = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtMerk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        txtKet = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setTitle("Searching Nota");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Kota tujuan");
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 21));

        txtKotaTujuan.setFont(new java.awt.Font("Dialog", 0, 12));
        txtKotaTujuan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtKotaTujuan.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtKotaTujuan.setName("txtKotaTujuan"); // NOI18N
        txtKotaTujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKotaTujuanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKotaTujuanKeyReleased(evt);
            }
        });
        jPanel1.add(txtKotaTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 50, 21));

        lblKota.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKota.setName("lblKota"); // NOI18N
        jPanel1.add(lblKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 330, 21));

        jLabel25.setText("Tgl. Berangkat");
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, 21));

        txtKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        txtKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtKapal.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtKapal.setName("txtKapal"); // NOI18N
        txtKapal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKapalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKapalKeyReleased(evt);
            }
        });
        jPanel1.add(txtKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 50, 21));

        lblTglBerangkat.setFont(new java.awt.Font("Dialog", 0, 12));
        lblTglBerangkat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblTglBerangkat.setName("lblTglBerangkat"); // NOI18N
        jPanel1.add(lblTglBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 120, 21));

        lblKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKapal.setName("lblKapal"); // NOI18N
        jPanel1.add(lblKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 330, 21));

        jLabel26.setText("Toko tujuan");
        jLabel26.setName("jLabel26"); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 21));

        txtToko.setFont(new java.awt.Font("Dialog", 0, 12));
        txtToko.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtToko.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtToko.setName("txtToko"); // NOI18N
        txtToko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTokoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTokoKeyReleased(evt);
            }
        });
        jPanel1.add(txtToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, 21));

        lblToko.setFont(new java.awt.Font("Dialog", 0, 12));
        lblToko.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblToko.setName("lblToko"); // NOI18N
        jPanel1.add(lblToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 330, 21));

        jLabel27.setText("Toko pengirim");
        jLabel27.setName("jLabel27"); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 21));

        txtPengirim.setFont(new java.awt.Font("Dialog", 0, 12));
        txtPengirim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPengirim.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtPengirim.setName("txtPengirim"); // NOI18N
        txtPengirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPengirimKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPengirimKeyReleased(evt);
            }
        });
        jPanel1.add(txtPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 50, 21));

        lblPengirim.setFont(new java.awt.Font("Dialog", 0, 12));
        lblPengirim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPengirim.setName("lblPengirim"); // NOI18N
        jPanel1.add(lblPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 330, 21));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tanggal Berangkat"));
        jPanel2.setName("jPanel2"); // NOI18N

        buttonGroup2.add(chkTglBerangkatAll);
        chkTglBerangkatAll.setText("All");
        chkTglBerangkatAll.setName("chkTglBerangkatAll"); // NOI18N
        chkTglBerangkatAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTglBerangkatAllActionPerformed(evt);
            }
        });

        buttonGroup2.add(chkTglBerangkatSelected);
        chkTglBerangkatSelected.setSelected(true);
        chkTglBerangkatSelected.setText("Selected");
        chkTglBerangkatSelected.setName("chkTglBerangkatSelected"); // NOI18N
        chkTglBerangkatSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTglBerangkatSelectedActionPerformed(evt);
            }
        });

        lblTglAwal.setText("Dari");
        lblTglAwal.setName("lblTglAwal"); // NOI18N

        lblTglAkhir.setText("Sampai");
        lblTglAkhir.setName("lblTglAkhir"); // NOI18N

        jDateBerangkat1.setName("jDateBerangkat1"); // NOI18N

        jDateBerangkat2.setName("jDateBerangkat2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkTglBerangkatAll, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblTglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(chkTglBerangkatSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateBerangkat1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateBerangkat2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(lblTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTglBerangkatSelected, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateBerangkat1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkTglBerangkatAll)
                            .addComponent(lblTglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateBerangkat2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 480, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tanggal Nota"));
        jPanel3.setName("jPanel3"); // NOI18N

        buttonGroup1.add(chkTglNotaAll);
        chkTglNotaAll.setSelected(true);
        chkTglNotaAll.setText("All");
        chkTglNotaAll.setName("chkTglNotaAll"); // NOI18N
        chkTglNotaAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTglNotaAllActionPerformed(evt);
            }
        });

        buttonGroup1.add(chkTglNotaSelected);
        chkTglNotaSelected.setText("Selected");
        chkTglNotaSelected.setName("chkTglNotaSelected"); // NOI18N
        chkTglNotaSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTglNotaSelectedActionPerformed(evt);
            }
        });

        lblTglAwal1.setText("Dari");
        lblTglAwal1.setName("lblTglAwal1"); // NOI18N

        lblTglAkhir1.setText("Sampai");
        lblTglAkhir1.setName("lblTglAkhir1"); // NOI18N

        jDateNota1.setEnabled(false);
        jDateNota1.setName("jDateNota1"); // NOI18N

        jDateNota2.setEnabled(false);
        jDateNota2.setName("jDateNota2"); // NOI18N

        jLabel31.setText("Kapal");
        jLabel31.setName("jLabel31"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkTglNotaAll, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblTglAwal1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(chkTglNotaSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(lblTglAkhir1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTglNotaSelected, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkTglNotaAll)
                            .addComponent(lblTglAwal1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblTglAkhir1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 480, 80));

        jLabel32.setText("Merk");
        jLabel32.setName("jLabel31"); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 21));

        lblSerialKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        lblSerialKapal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSerialKapal.setText("0");
        lblSerialKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblSerialKapal.setName("lblSerialKapal"); // NOI18N
        jPanel1.add(lblSerialKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 90, 21));

        jLabel33.setText("Kapal");
        jLabel33.setName("jLabel32"); // NOI18N
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 21));

        txtMerk.setFont(new java.awt.Font("Dialog", 0, 12));
        txtMerk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtMerk.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtMerk.setName("txtMerk"); // NOI18N
        txtMerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMerkKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMerkKeyReleased(evt);
            }
        });
        jPanel1.add(txtMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 310, 21));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 330));

        jButton1.setText("Preview");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 80, 30));

        jButton2.setText("Close");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 70, 30));

        jLabel28.setText("Satuan");
        jLabel28.setName("jLabel28"); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 20));

        jLabel29.setText("Item");
        jLabel29.setName("jLabel29"); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 20));

        jLabel30.setText("Ket");
        jLabel30.setName("jLabel30"); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 20));

        txtSatuan.setName("txtSatuan"); // NOI18N
        getContentPane().add(txtSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 400, -1));

        txtItem.setName("txtItem"); // NOI18N
        getContentPane().add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 400, -1));

        txtKet.setName("txtKet"); // NOI18N
        getContentPane().add(txtKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 400, -1));

        jButton3.setText("Clear");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 421, 84, 28));

        jCheckBox1.setText("Borderless");
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 423, 126, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-528)/2, (screenSize.height-492)/2, 528, 492);
    }// </editor-fold>//GEN-END:initComponents

private void txtKotaTujuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKotaTujuanKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtKotaTujuanKeyPressed

private void txtKotaTujuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKotaTujuanKeyReleased
    try {
        String sCari = txtKotaTujuan.getText();
        switch (evt.getKeyCode()) {

            case java.awt.event.KeyEvent.VK_ENTER: {
                if (lst.isVisible()) {
                    Object[] obj = lst.getOResult();
                    if (obj.length > 0) {
                        txtKotaTujuan.setText(obj[0].toString());
                        lblKota.setText(obj[1].toString());
                        //lblAlamatToko.setText(obj[2].toString());
                        lst.setVisible(false);
                    }
                }
                break;
            }
            case java.awt.event.KeyEvent.VK_DELETE: {
                lst.setFocusable(true);
                lst.requestFocus();

                break;
            }
            case java.awt.event.KeyEvent.VK_ESCAPE: {
                lst.setVisible(false);
                txtKotaTujuan.setText("");
                lblKota.setText("");
            }
            case java.awt.event.KeyEvent.VK_DOWN: {
                if (lst.isVisible()) {

                    lst.setFocusableWindowState(true);
                    lst.setVisible(true);
                    lst.requestFocus();
                }
                break;
            }
            default: {
                if (!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")) {
//                        if(txtSupplier.getText().trim().equalsIgnoreCase("")){
//                            JOptionPane.showMessageDialog(this, "Silakan isi supplier terlebih dulu!");
//                            txtSupplier.requestFocus();
//                            return;
//                        }   
                    String sQry = "select kode_kota, nama_kota "
                            + "from kota where kode_kota||nama_kota ilike '%" + sCari + "%' order by nama_kota";

                    //System.out.println(sQry);
                    lst.setSQuery(sQry);

                    lst.setBounds(this.getX() + this.jPanel1.getX() + this.txtKotaTujuan.getX() + Utama.iLeft + 17,
                            this.getY() + this.jPanel1.getY() + this.txtKotaTujuan.getY() + txtKotaTujuan.getHeight() + Utama.iTop + 77,
                            txtKotaTujuan.getWidth() + lblKota.getWidth() + 5,
                            150);
                    lst.setFocusableWindowState(false);
                    lst.setTxtCari(txtKotaTujuan);
                    lst.setLblDes(new javax.swing.JLabel[]{lblKota});
                    lst.setColWidth(0, txtKotaTujuan.getWidth());
                    lst.setColWidth(1, lblKota.getWidth());
                    if (lst.getIRowCount() > 0) {
                        lst.setVisible(true);
                        requestFocusInWindow();
                        txtKotaTujuan.requestFocus();
                    } else {
                        txtKotaTujuan.setText("");
                        lblKota.setText("");
                        lst.setVisible(false);
                        txtKotaTujuan.requestFocus();
                    }
                }
                break;
            }
        }
    } catch (SQLException se) {
        System.out.println(se.getMessage());
    }
}//GEN-LAST:event_txtKotaTujuanKeyReleased

private void txtKapalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKapalKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtKapalKeyPressed

private void txtKapalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKapalKeyReleased
    //        String sQry="select distinct kon.kode_kapal, nama_kapal " +
    //                                "from kontainer kon " +
    //                                "inner join kapal on kapal.kode_kapal=kon.kode_kapal " +
    //                                "where (kon.kode_kapal||nama_kapal) iLike '%"+txtKapal.getText()+"%' limit 100";
    try {
        switch (evt.getKeyCode()) {

            case java.awt.event.KeyEvent.VK_ENTER: {
                if (lst.isVisible()) {
                    Object[] obj = lst.getOResult();
                    if (obj.length > 0) {
                        txtKapal.setText(obj[0].toString());
                        lblKapal.setText(obj[1].toString());
                        lst.setVisible(false);
                    }
                }
                break;
            }
            case java.awt.event.KeyEvent.VK_DELETE: {
                lst.setFocusable(true);
                lst.requestFocus();

                break;
            }
            case java.awt.event.KeyEvent.VK_ESCAPE: {
                lst.setVisible(false);
                txtKapal.setText("");
                lblKapal.setText("");
                lblTglBerangkat.setText("");
                lblSerialKapal.setText("");
                txtKapal.requestFocus();
                break;
            }
            case java.awt.event.KeyEvent.VK_DOWN: {
                if (lst.isVisible()) {

                    lst.setFocusableWindowState(true);
                    lst.setVisible(true);
                    lst.requestFocus();
                }
                break;
            }
            default: {
                if (!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")) {
                    String sQry = "select tj.kode_kapal, nama_kapal , to_Char(tgl_berangkat, 'dd-MM-yyyy') as tgl_berangkat, "
                            + "serial_kode, coalesce(nama_kota,'') as kota_tujuan "
                            + "from nota_kapal_tujuan tj "
                            + "inner join kapal on kapal.kode_kapal=tj.kode_kapal "
                            + "left join kota on kode_kota=kota_tujuan "
                            + "where (tj.kode_kapal||nama_kapal||coalesce(nama_kota,'') ) iLike '%" + txtKapal.getText() + "%' and active=true "
                            + "and kota_tujuan like '%" + txtKotaTujuan.getText() + "%' limit 100";

                    //System.out.println(sQry);
                    lst.setSQuery(sQry);

                    lst.setBounds(Utama.iLeft + this.getX() + this.jPanel1.getX() + this.txtKapal.getX() + 6,
                            Utama.iTop + this.getY() + this.jPanel1.getY() + this.txtKapal.getY() + txtKapal.getHeight() + 57,
                            txtKapal.getWidth() + lblKapal.getWidth() + lblTglBerangkat.getWidth(),
                            150);
                    lst.setFocusableWindowState(false);
                    lst.setTxtCari(txtKapal);
                    lst.setLblDes(new javax.swing.JLabel[]{lblKapal, lblTglBerangkat, lblSerialKapal});
                    lst.setColWidth(0, txtKapal.getWidth());
                    lst.setColWidth(1, lblKapal.getWidth());


                    if (lst.getIRowCount() > 0) {
                        lst.setVisible(true);
                        requestFocusInWindow();
                        txtKapal.requestFocus();
                    } else {
                        lst.setVisible(false);
                        txtKapal.setText("");
                        lblKapal.setText("");
                        lblSerialKapal.setText("0");
                        lblTglBerangkat.setText("");
                        txtKapal.requestFocus();
                    }
                }
                break;
            }
        }
    } catch (SQLException se) {
        System.out.println(se.getMessage());
    }
}//GEN-LAST:event_txtKapalKeyReleased

private void txtTokoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTokoKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtTokoKeyPressed

private void txtTokoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTokoKeyReleased
    try {
        String sQry = "select c.kode_cust as kode,  coalesce(c.nama,'') as toko "
                + "from customer c inner join merk on c.kode_cust=merk.kode_cust "
                + "left join kota on kota.kode_kota=c.kota "
                + "where (coalesce(c.nama,'')||coalesce(nama_kota,'')) iLike '%" + txtToko.getText() + "%' "
                + "and c.kota like '%" + Utama.sKodeKota + "%' "
                + "group by c.kode_cust, coalesce(c.nama,''), coalesce(nama_kota,'') "
                + "order by coalesce(c.nama,'')";
        switch (evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_ENTER: {
                if (lst.isVisible()) {
                    Object[] obj = lst.getOResult();
                    if (obj.length > 0) {
                        txtToko.setText(obj[0].toString());
                        lblToko.setText(obj[1].toString());
                        lst.setVisible(false);
                    }
                }
                break;
            }
            case java.awt.event.KeyEvent.VK_DELETE: {
                lst.setFocusable(true);
                lst.requestFocus();

                break;
            }
            case java.awt.event.KeyEvent.VK_ESCAPE: {
                lst.setVisible(false);
                txtToko.setText("");
                lblToko.setText("");

                txtToko.requestFocus();
                break;
            }
            case java.awt.event.KeyEvent.VK_DOWN: {
                if (lst.isVisible()) {

                    lst.setFocusableWindowState(true);
                    lst.setVisible(true);
                    lst.requestFocus();
                }
                break;
            }
            default: {
                if (!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")) {
                    System.out.println(sQry);
                    lst.setSQuery(sQry);

                    lst.setBounds(Utama.iLeft + this.getX() + this.jPanel1.getX() + this.txtToko.getX() + 19,
                            Utama.iTop + this.getY() + this.jPanel1.getY() + this.txtToko.getY() + txtToko.getHeight() + 77,
                            txtToko.getWidth() + lblToko.getWidth(),
                            150);
                    lst.setFocusableWindowState(false);
                    lst.setTxtCari(txtToko);
                    lst.setLblDes(new javax.swing.JLabel[]{lblToko});
                    lst.setColWidth(0, txtToko.getWidth());
                    lst.setColWidth(1, lblToko.getWidth());

                    if (lst.getIRowCount() > 0) {
                        lst.setVisible(true);
                        requestFocusInWindow();
                        txtToko.requestFocus();
                    } else {
                        lst.setVisible(false);
                        txtToko.setText("");
                        lblToko.setText("");
                        txtToko.requestFocus();
                    }
                }
                break;
            }
        }
    } catch (SQLException se) {
        System.out.println(se.getMessage());
    }
}//GEN-LAST:event_txtTokoKeyReleased

private void txtPengirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPengirimKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtPengirimKeyPressed

private void txtPengirimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPengirimKeyReleased
// TODO add your handling code here:
    try {
        String sQry = "select kode_toko, coalesce(nama,'') as nama, coalesce(nama,'') as kepada "
                + "from toko where coalesce(nama,'') iLike '%" + txtPengirim.getText() + "%' order by coalesce(nama,'') ";

        switch (evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_ENTER: {
                if (lst.isVisible()) {
                    Object[] obj = lst.getOResult();
                    if (obj.length > 0) {
                        txtPengirim.setText(obj[0].toString());
                        lblPengirim.setText(obj[1].toString());
                        lst.setVisible(false);
                    }
                }
                break;
            }
            case java.awt.event.KeyEvent.VK_DELETE: {
                lst.setFocusable(true);
                lst.requestFocus();

                break;
            }
            case java.awt.event.KeyEvent.VK_ESCAPE: {
                lst.setVisible(false);
                txtPengirim.setText("");
                lblPengirim.setText("");

                txtPengirim.requestFocus();
                break;
            }
            case java.awt.event.KeyEvent.VK_DOWN: {
                if (lst.isVisible()) {

                    lst.setFocusableWindowState(true);
                    lst.setVisible(true);
                    lst.requestFocus();
                }
                break;
            }
            default: {
                if (!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")) {
                    //System.out.println(sQry);
                    lst.setSQuery(sQry);

                    lst.setBounds(Utama.iLeft + this.getX() + this.jPanel1.getX() + this.txtToko.getX() + 19,
                            Utama.iTop + this.getY() + this.jPanel1.getY() + this.txtPengirim.getY() + txtPengirim.getHeight() + 77,
                            txtPengirim.getWidth() + lblPengirim.getWidth(),
                            150);
                    lst.setFocusableWindowState(false);
                    lst.setTxtCari(txtPengirim);
                    lst.setLblDes(new javax.swing.JLabel[]{lblPengirim});
                    lst.setColWidth(0, txtPengirim.getWidth());
                    lst.setColWidth(1, lblPengirim.getWidth());


                    if (lst.getIRowCount() > 0) {
                        lst.setVisible(true);
                        requestFocusInWindow();
                        txtPengirim.requestFocus();
                    } else {
                        lst.setVisible(false);
                        txtPengirim.setText("");
                        lblPengirim.setText("");
                        txtPengirim.requestFocus();
                    }
                }
                break;
            }
        }
    } catch (SQLException se) {
        System.out.println(se.getMessage());
    }
}//GEN-LAST:event_txtPengirimKeyReleased

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    lst = new ListRsbm();
    lst.setVisible(false);
    lst.setSize(500, 200);
    lst.con = conn;

    modelTrx = new DefaultListModel();

}//GEN-LAST:event_formInternalFrameOpened

private void txtMerkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMerkKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_txtMerkKeyPressed

private void txtMerkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMerkKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtMerkKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        HashMap reportParam = new HashMap();
        JasperReport jasperReport = null;
        String sRpt = (jCheckBox1.isSelected() ? "nota_daftar_tagihan_lookup_b" : "nota_daftar_tagihan_lookup");

        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        reportParam.put("kode_kota", txtKotaTujuan.getText());
        reportParam.put("serial_kapal", Integer.parseInt(lblSerialKapal.getText()));
        reportParam.put("tujuan", txtToko.getText());
        reportParam.put("merk", txtMerk.getText().trim());
        reportParam.put("pengirim", txtPengirim.getText());
        reportParam.put("b_tgl_nota_all", chkTglNotaSelected.isSelected());
        reportParam.put("tgl_nota1", dFormat.format(jDateNota1.getDate()));
        reportParam.put("tgl_nota2", dFormat.format(jDateNota2.getDate()));
        reportParam.put("b_tgl_brgkt_all", chkTglBerangkatSelected.isSelected());
        reportParam.put("tgl_brgkt1", dFormat.format(jDateBerangkat1.getDate()));
        reportParam.put("tgl_brgkt2", dFormat.format(jDateBerangkat2.getDate()));
        reportParam.put("item", txtItem.getText());
        reportParam.put("ket", txtKet.getText());
        reportParam.put("sat", txtSatuan.getText());

        jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource("Reports/" + sRpt + ".jasper"));

        //jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource("Reports_2/packing_list_per_kontainer.jasper"));
        JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);

        if (print.getPages().isEmpty()) {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            return;
        }
        print.setOrientation(jasperReport.getOrientation());
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        JasperViewer.viewReport(print, false);

    } catch (JRException je) {
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        System.out.println(je.getMessage());
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void chkTglNotaAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTglNotaAllActionPerformed
    jDateNota1.setEnabled(!chkTglNotaAll.isSelected());
    jDateNota2.setEnabled(!chkTglNotaAll.isSelected());
}//GEN-LAST:event_chkTglNotaAllActionPerformed

private void chkTglNotaSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTglNotaSelectedActionPerformed
    jDateNota1.setEnabled(!chkTglNotaAll.isSelected());
    jDateNota2.setEnabled(!chkTglNotaAll.isSelected());
}//GEN-LAST:event_chkTglNotaSelectedActionPerformed

private void chkTglBerangkatAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTglBerangkatAllActionPerformed
    jDateBerangkat1.setEnabled(!chkTglBerangkatAll.isSelected());
    jDateBerangkat2.setEnabled(!chkTglBerangkatAll.isSelected());
}//GEN-LAST:event_chkTglBerangkatAllActionPerformed

private void chkTglBerangkatSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTglBerangkatSelectedActionPerformed
    jDateBerangkat1.setEnabled(!chkTglBerangkatAll.isSelected());
    jDateBerangkat2.setEnabled(!chkTglBerangkatAll.isSelected());
}//GEN-LAST:event_chkTglBerangkatSelectedActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    udfClear();
}//GEN-LAST:event_jButton3ActionPerformed

private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
    Utama.isRptLookup = false;
}//GEN-LAST:event_formInternalFrameClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton chkTglBerangkatAll;
    private javax.swing.JRadioButton chkTglBerangkatSelected;
    private javax.swing.JRadioButton chkTglNotaAll;
    private javax.swing.JRadioButton chkTglNotaSelected;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private org.jdesktop.swingx.JXDatePicker jDateBerangkat1;
    private org.jdesktop.swingx.JXDatePicker jDateBerangkat2;
    private org.jdesktop.swingx.JXDatePicker jDateNota1;
    private org.jdesktop.swingx.JXDatePicker jDateNota2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblKapal;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblPengirim;
    private javax.swing.JLabel lblSerialKapal;
    private javax.swing.JLabel lblTglAkhir;
    private javax.swing.JLabel lblTglAkhir1;
    private javax.swing.JLabel lblTglAwal;
    private javax.swing.JLabel lblTglAwal1;
    private javax.swing.JLabel lblTglBerangkat;
    private javax.swing.JLabel lblToko;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtKapal;
    private javax.swing.JTextField txtKet;
    private javax.swing.JTextField txtKotaTujuan;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtPengirim;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtToko;
    // End of variables declaration//GEN-END:variables
}
