/*
 * frmRptKasir.java
 *
 * Created on November 30, 2005, 7:04 PM
 */

package tpjkeuangan;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author  root
 */
public class FrmRptTagihanPerKapal extends javax.swing.JInternalFrame {
    
    private Connection conn;
    private String sKodeJenis="";
    private String sUser="";
    private DefaultListModel modelJenis, modelTrx;
    private ListRsbm lst;
    
    public void setCon(Connection con){
        conn=con;
    }
    /** Creates new form frmRptKasir */
    public FrmRptTagihanPerKapal() {
        initComponents();
    }

    void setUserName(String sUserName) {
        sUser="";
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPreview = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtKapal = new javax.swing.JTextField();
        lblKotaTujuan = new javax.swing.JLabel();
        lblKapal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTglBerangkat = new javax.swing.JLabel();
        lblSerialKapal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnTambahItem1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setTitle("Tagihan Per Kapal");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/preview.png"))); // NOI18N
        btnPreview.setMnemonic('P');
        btnPreview.setText("Preview");
        btnPreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 148, 90, 100));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tujuan");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 41, 80, -1));

        txtKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        txtKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtKapal.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtKapal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKapalFocusLost(evt);
            }
        });
        txtKapal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKapalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKapalKeyReleased(evt);
            }
        });
        jPanel2.add(txtKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 7, 64, 24));

        lblKotaTujuan.setBackground(new java.awt.Color(255, 255, 255));
        lblKotaTujuan.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKotaTujuan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKotaTujuan.setOpaque(true);
        jPanel2.add(lblKotaTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 32, 382, 24));

        lblKapal.setBackground(new java.awt.Color(255, 255, 255));
        lblKapal.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKapal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblKapal.setOpaque(true);
        jPanel2.add(lblKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 7, 320, 24));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Tgl. Berangkat");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 9, 90, 20));

        lblTglBerangkat.setBackground(new java.awt.Color(255, 255, 255));
        lblTglBerangkat.setFont(new java.awt.Font("Dialog", 0, 12));
        lblTglBerangkat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblTglBerangkat.setOpaque(true);
        jPanel2.add(lblTglBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 7, 90, 24));
        jPanel2.add(lblSerialKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 35, 90, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KAPAL");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 13, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 676, 80));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Umum (Per kapal berangkat)", "Rekap tagihan per Nota", "Rekap tagihan per Customer" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, 490, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Pilih Jenis Laporan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 154, 280, -1));

        btnTambahItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/Exit_1.png"))); // NOI18N
        btnTambahItem1.setText("Tutup");
        btnTambahItem1.setToolTipText("Tutup aplikasi pembayaran");
        btnTambahItem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambahItem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambahItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahItem1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 148, 90, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/report_header.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, 680, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-701)/2, (screenSize.height-287)/2, 701, 287);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Utama.isRptTagihanPerKapal=false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        lst = new ListRsbm();
        lst.setVisible(false);
        lst.setSize(500, 200);
        lst.con = conn;
            
        modelTrx=new DefaultListModel();
        jList1.setSelectedIndex(0);
        
    }//GEN-LAST:event_formInternalFrameOpened
                    
    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        udfPrint();
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void txtKapalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKapalFocusLost
        
    }//GEN-LAST:event_txtKapalFocusLost

    private void txtKapalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKapalKeyPressed
        
    }//GEN-LAST:event_txtKapalKeyPressed

    private void txtKapalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKapalKeyReleased
        //        String sQry="select distinct kon.kode_kapal, nama_kapal " +
        //                                "from kontainer kon " +
        //                                "inner join kapal on kapal.kode_kapal=kon.kode_kapal " +
        //                                "where (kon.kode_kapal||nama_kapal) iLike '%"+txtKapal.getText()+"%' limit 100";
        try {
            switch(evt.getKeyCode()) {
                
                case java.awt.event.KeyEvent.VK_ENTER : {
                    if (lst.isVisible()){
                        Object[] obj = lst.getOResult();
                        if (obj.length > 0) {
                            txtKapal.setText(obj[0].toString());
                            lblKapal.setText(obj[1].toString());
                            lst.setVisible(false);
                        }
                    }
                    break;
                }
                case java.awt.event.KeyEvent.VK_DELETE: {
                    lst.setFocusable(true);
                    lst.requestFocus();
                    
                    break;
                }
                case java.awt.event.KeyEvent.VK_ESCAPE: {
                    lst.setVisible(false);
                    txtKapal.setText("");
                    lblKapal.setText("");
                    txtKapal.requestFocus();
                    break;
                }
                case java.awt.event.KeyEvent.VK_DOWN: {
                    if (lst.isVisible()){
                        
                        lst.setFocusableWindowState(true);
                        lst.setVisible(true);
                        lst.requestFocus();
                    }
                    break;
                }
                default : {
                    if(!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")){
                        String sQry="select tj.kode_kapal, nama_kapal , to_Char(tgl_berangkat, 'dd-MM-yyyy') as tgl_berangkat, " +
                                "coalesce(nama_kota,'') as kota_tujuan, serial_kode " +
                                "from nota_kapal_tujuan tj " +
                                "inner join kapal on kapal.kode_kapal=tj.kode_kapal " +
                                "left join kota on kode_kota=kota_tujuan " +
                                "where (tj.kode_kapal||nama_kapal||coalesce(nama_kota,'') ) iLike '%"+txtKapal.getText()+"%' and active=true limit 100";
                        
                        System.out.println(sQry);
                        lst.setSQuery(sQry);
                        
                        lst.setBounds(this.txtKapal.getLocationOnScreen().x,
                                this.txtKapal.getLocationOnScreen().y + txtKapal.getHeight(),
                                txtKapal.getWidth()+lblKapal.getWidth()+jLabel12.getWidth()+lblTglBerangkat.getWidth(),
                                150);
                        lst.setFocusableWindowState(false);
                        lst.setTxtCari(txtKapal);
                        lst.setLblDes(new javax.swing.JLabel[]{lblKapal, lblTglBerangkat, lblKotaTujuan, lblSerialKapal});
                        lst.setColWidth(0, txtKapal.getWidth());
                        lst.setColWidth(1, lblKapal.getWidth());
                        
                        
                        if(lst.getIRowCount()>0){
                            lst.setVisible(true);
                            requestFocusInWindow();
                            txtKapal.requestFocus();
                        } else{
                            lst.setVisible(false);
                            txtKapal.setText("");
                            lblKapal.setText("");
                            txtKapal.requestFocus();
                        }
                    }
                    break;
                }
            }
        } catch (SQLException se) {System.out.println(se.getMessage());}
    }//GEN-LAST:event_txtKapalKeyReleased

    private void btnTambahItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTambahItem1ActionPerformed

    void setUser(String sUser) {
        this.sUser=sUser;
    }

        
    
    private void udfPrint() {
        if(Integer.parseInt(lblSerialKapal.getText())> 0){
            try {
                String sKapalBerangkat=lblKapal.getText() +" ~ Tgl. "+lblTglBerangkat.getText();
                HashMap reportParam = new HashMap();
                JasperReport jasperReport = null;
                reportParam.put("serial_kapal", Integer.parseInt(lblSerialKapal.getText()));
                reportParam.put("kota_tujuan", lblKotaTujuan.getText());
                reportParam.put("kapal_berangkat", sKapalBerangkat);

                switch(jList1.getSelectedIndex()){
                    case 0:{ //Umum semua nota per Kapal berangkat
                        jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/nota_daftar_tagihan_per_kapal_per_tgl_berangkat.jasper"));
//                        JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
//                        print.setOrientation(jasperReport.getOrientation());
//                        JasperViewer.viewReport(print, false);
                        break;
                    }
                    case 1:{ //Rekap tagihan per Nota
                        
                        jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/rekap_per_kapal_per_nota.jasper"));
//                        JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
//                        print.setOrientation(jasperReport.getOrientation());
//                        JasperViewer.viewReport(print, false);
                        break;
                    }
                    case 2:{ //Rekap tagihan per Customer
                        jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/rekap_per_kapal_per_customer.jasper"));
//                        JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
//                        print.setOrientation(jasperReport.getOrientation());
//                        JasperViewer.viewReport(print, false);
                        break;
                    }
                    default:{
                        jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/nota_daftar_tagihan_per_kapal_per_tgl_berangkat.jasper"));
//                        JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
//                        print.setOrientation(jasperReport.getOrientation());
//                        JasperViewer.viewReport(print, false);
                        break;
                    }
                }
                
                JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
                if(print.getPages().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Report tidak ditemukan!");
                    return;
                }
                print.setOrientation(jasperReport.getOrientation());
                JasperViewer.viewReport(print, false);

            } catch (JRException je) {
                System.out.println(je.getMessage());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRptKasir().setVisible(true);
            }
        });
    }
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPreview;
    public javax.swing.JButton btnTambahItem1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JList jList1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblKapal;
    public javax.swing.JLabel lblKotaTujuan;
    public javax.swing.JLabel lblSerialKapal;
    public javax.swing.JLabel lblTglBerangkat;
    public javax.swing.JTextField txtKapal;
    // End of variables declaration//GEN-END:variables
    
}
